logging:
  level:
    root: info
    com:
      zaxxer: warn
    org:
      apache: warn
      h2: warn
      hibernate: warn
      springframework: warn

  pattern:
    # special characters need to be escaped / quoted
    console: '%clr([%thread] [%date{HH:mm:ss.SSS}]){faint} %clr(%2p) %clr(%-40.40logger{36}){cyan} %m%n%wex'

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: admin
    password: passw0rd


rabbitmq:
  exchange:
    name: 'orders'
  routing:
    key: 'products-key'
  queue:
    name: 'order.create'