logging:
  level:
    root: info
    org:
      apache: warn
      springframework: warn

  pattern:
    # special characters need to be escaped / quoted
    console: '%clr([%thread] [%date{HH:mm:ss.SSS}]){faint} %clr(%2p) %clr(%-40.40logger{36}){cyan} %m%n%wex'

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: admin
    password: passw0rd