logging:
  level:
    root: info
    com:
      zaxxer: warn
    org:
      apache: warn
      h2: warn
      hibernate: warn
      springframework: warn

  pattern:
    # special characters need to be escaped / quoted
    console: '%clr([%thread] [%date{HH:mm:ss.SSS}]){faint} %clr(%2p) %clr(%-40.40logger{36}){cyan} %m%n%wex'

spring:
  datasource:
    # in-memory database
    url: jdbc:h2:mem:failed-messages

    # on disk database
    #url: jdbc:h2:~/failed-messages

    username: sa
    password: aVeryComplexPassword

  jpa:
    open-in-view: false
    properties:
      hibernate:
      show_sql: false
      format_sql: true

  sql:
    init:
      platform: h2

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: admin
    password: passw0rd